version: "3.8"

services:
   nextops-api:
      build:
         context: ./NextOps.Api
         dockerfile: Dockerfile
      ports:
         - "5000:80"
      environment:
         - ASPNETCORE_ENVIRONMENT=Development
      volumes:
         - ./NextOps.Api:/app
